version: "3.3"
  
services:
  db:
    image: mysql
    container_name: mysql
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root 
      MYSQL_DATABASE: project
      MYSQL_USER: user
      MYSQL_PASSWORD: root

  phpmyadmin: 
    image: phpmyadmin/phpmyadmin
    container_name: myadmin
    ports:
      - "8082:80" 
    environment: 
        PMA_HOST: db
        PMA_USER: root
        PMA_PASSWORD: root
    depends_on:
      - db 
    restart: always

  php-fpm:
    build: ./src/php
    container_name: myphp
    ports:
      - "9000"
    depends_on:
      - phpmyadmin
    restart: always
    volumes:
      - $HOME/Event-Scheduler/src:/var/www/html
    networks:
      - app-network

  nginx:
    image: nginx
    container_name: mynginx
    ports:
      - "8081:80"
    volumes:
      - $HOME/Event-Scheduler/src/nginx.ini:/etc/nginx/conf.d/default.conf
      - $HOME/Event-Scheduler/src/php-fpm.conf:/etc/php/7.4/fpm/php-fpm.conf
      - $HOME/Event-Scheduler/src/www.conf:/etc/php/7.4/fpm/pool.d/www.conf
      - $HOME/Event-Scheduler/src:/var/www/html
    depends_on:
      - php-fpm
    restart: always
    networks:
      - app-network    

networks:
  app-network:
    driver: bridge    

