version: "3.3"
  
services:
  db-master:
    image: mysql:5.6
    container_name: mysql_master
    ports:
      - "3306:3306"
    restart: always
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_REPLICATION_MODE: master
      MYSQL_REPLICATION_USER: repl_root
      MYSQL_REPLICATION_PASSWORD: root
      MYSQL_DATABASE: project
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    networks:
      - app-network

  db-replica:
    image: mysql:5.6
    container_name: mysql_replica
    depends_on:
      - db-master
    ports:
      - "4406:3306"
    restart: always
    environment:
      MYSQL_MASTER_ROOT_PASSWORD: root
      MYSQL_REPLICATION_MODE: slave
      MYSQL_REPLICATION_USER: repl_root
      MYSQL_REPLICATION_PASSWORD: root
      MYSQL_MASTER_HOST: db-master
      MYSQL_MASTER_PASSWORD: root
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: project
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: myadmin
    ports:
      - "8082:80"
    environment:
        PMA_HOST: db-master
        PMA_USER: root
        PMA_PASSWORD: root
        PMA_PORT: 3306
    depends_on:
      - db-master
    restart: always
    networks:
      - app-network
  php-fpm:
    build: ./src/php
    container_name: myphp
    ports:
      - "9000"
    depends_on:
      - phpmyadmin
    restart: always
    volumes:
      - $HOME/Event-Scheduler/src:/var/www/html
    networks:
      - app-network
  nginx:
    image: nginx
    container_name: mynginx
    ports:
      - "8081:80"
    volumes:
      - $HOME/Event-Scheduler/src/nginx.ini:/etc/nginx/conf.d/default.conf
      - $HOME/Event-Scheduler/src/php-fpm.conf:/etc/php/7.4/fpm/php-fpm.conf
      - $HOME/Event-Scheduler/src/www.conf:/etc/php/7.4/fpm/pool.d/www.conf
      - $HOME/Event-Scheduler/src:/var/www/html
    depends_on:
      - php-fpm
    restart: always
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
